export enum AuditActionEnum {
  ENTITY_CREATED = 'ENTITY_CREATED',
  ENTITY_UPDATED = 'ENTITY_UPDATED',
  ENTITY_REMOVED = 'ENTITY_REMOVED',
  SANCTIONED_ENTITY_CREATED = 'SANCTIONED_ENTITY_CREATED',
  SANCTIONED_ENTITY_STATUS_CHANGED = 'SANCTIONED_ENTITY_STATUS_CHANGED',
  SANCTIONED_ENTITY_REMOVED = 'SANCTIONED_ENTITY_REMOVED',
  REVIEW_CREATED = 'REVIEW_CREATED',
  DISTRIBUTION_STARTED = 'DISTRIBUTION_STARTED',
  DISTRIBUTION_COMPLETED = 'DISTRIBUTION_COMPLETED',
  DISTRIBUTION_FAILED = 'DISTRIBUTION_FAILED',
}
